spring.application.name=auto-parts
server.port=${PORT:8080}

# Database connection - Lấy từ biến môi trường của Render
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# Hibernate/JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT (dev settings)
app.jwt.secret=${JWT_SECRET:PLEASE_CHANGE_THIS_DEV_SECRET_TO_A_LONG_RANDOM_STRING_32_CHARS_MIN}
app.jwt.expiration-ms=86400000

# Inspection uploads
app.inspection.upload-dir=uploads/inspections

# Cloudinary Config
cloudinary.cloud-name=dxb3jbbnj
cloudinary.api-key=517741449648916
cloudinary.api-secret=8-Cl48UrVQv-FR8H93HYj6umzxE
cloudinary.upload-preset=autoPartQC

# VNPay Config - Lấy đường dẫn Frontend từ biến môi trường
vnpay.vnp_Url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.vnp_ReturnUrl=${FRONTEND_URL}/payment-success
vnpay.vnp_TmnCode=RM0KHMGJ
vnpay.vnp_HashSecret=ZAHW0CIXJEBC69AV4PMACE0YRP7FUUBZ
vnpay.vnp_Version=2.1.0
vnpay.vnp_Command=pay