spring.application.name=auto-parts
server.port=${PORT:8080}

# Database connection - Lấy từ biến môi trường của Render
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# Hibernate/JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT (dev settings)
app.jwt.secret=${JWT_SECRET:PLEASE_CHANGE_THIS_DEV_SECRET_TO_A_LONG_RANDOM_STRING_32_CHARS_MIN}
app.jwt.expiration-ms=86400000

# Inspection uploads
app.inspection.upload-dir=uploads/inspections

# Cloudinary Config
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
cloudinary.upload-preset=autoPartQC

# VNPay Config
vnpay.vnp_Url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.vnp_ReturnUrl=${FRONTEND_URL}/payment-success
vnpay.vnp_TmnCode=${VNPAY_TMN_CODE}
vnpay.vnp_HashSecret=${VNPAY_HASH_SECRET}
vnpay.vnp_Version=2.1.0
vnpay.vnp_Command=pay


# Python AI Server URL (Chạy local mặc định port 8000 của FastAPI, lên Render lấy URL thật)
app.ai-server.url=${PYTHON_SERVER_URL:http://localhost:8000}