POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "manager01",
  "password": "password123"
}

> {%
    // Script tự động lưu token vào biến môi trường của IntelliJ
    client.global.set("auth_token", response.body.token);
%}

### 11. Tạo một Session mới để chuẩn bị test ảnh
POST http://localhost:8080/api/inspections/sessions
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "lotCode": "LOT-AI-TEST-ALTERNATOR",
  "partId": 27
}

> {%
    // Lưu tạm ID của session vừa tạo vào biến để bước sau dùng luôn
    client.global.set("session_id", response.body.id);
%}

### 12. Bắn ảnh cho AI phân tích (Test Endpoint Quan Trọng Nhất)
POST http://localhost:8080/api/inspections/sessions/{{session_id}}/inspect
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=Boundary123456789

--Boundary123456789
Content-Disposition: form-data; name="image"; filename="2.jpg"
Content-Type: image/jpeg

< E:\data set\test\AIR COMPRESSOR\1.jpg
--Boundary123456789--